version: '3'
services:

  stateless-auth-db:
    container_name: stateless-auth-db
    image: postgres:latest
    environment:
      - POSTGRES_DB=auth_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - auth-network
    ports:
      - 5432:5432

  stateful-auth-db:
    container_name: stateful-auth-db
    image: postgres:latest
    environment:
      - POSTGRES_DB=auth_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - auth-network
    ports:
      - 5433:5432

  token-redis:
    container_name: token-redis
    image: redis:latest
    networks:
      - auth-network
    ports:
      - 6379:6379

  stateless-auth-api:
    container_name: stateless-auth-api
    build: './stateless/stateless-auth-api'
    depends_on:
      - stateless-auth-db
    environment:
      - PORT=8080
      - DB_HOST=stateless-auth-db
      - DB_PORT=5432
      - DB_NAME=auth_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    networks:
      - auth-network
    ports:
      - 8080:8080
  
  stateless-any-api:
    container_name: stateless-any-api
    build: './stateless/stateless-any-api'
    environment:
      - PORT=8081
    networks:
      - auth-network
    ports:
      - 8081:8081

  stateful-auth-api:
    container_name: stateful-auth-api
    build: './stateful/stateful-auth-api'
    depends_on:
      - stateful-auth-db
    environment:
      - PORT=8082
      - DB_HOST=stateful-auth-db
      - DB_PORT=5432
      - DB_NAME=auth_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    networks:
      - auth-network
    ports:
      - 8082:8082

  stateful-any-api:
    container_name: stateful-any-api
    build: './stateful/stateful-any-api'
    environment:
      - PORT=8083
    networks:
      - auth-network
    ports:
      - 8083:8083

networks:
  auth-network:
    driver: bridge